spring:
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/quarkus_test
    username: quarkus_test
    password: quarkus_test
    driverClassName: org.postgresql.Driver

logging:
  level:
    org:
      hibernate:
        SQL: debug
