spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springcloud
    username: springcloud
    password: 123
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true