spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/quarkus_test"
    username: quakurs_test
    password: quarkus_test
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
    hibernate:
      ddl-auto: create

logging:
  level:
    org:
      hibernate:
        SQL: debug

# spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true