spring:
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    # schema: classpath:/schema.sql
    platform: postgres
    url: jdbc:postgresql://springcloud-postgres:5432/quarkus_test
    username: quarkus_test
    password: quarkus_test
    driverClassName: org.postgresql.Driver

logging:
  level:
    org:
      hibernate:
        SQL: debug

example:
  hello: hello